// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzwmg80YlfdAtkcoEZjaOec2scf6FPee0',
    appId: '1:338017368100:web:5d51d7c29b9a4913a340b1',
    messagingSenderId: '338017368100',
    projectId: 'flutter-web-portfolio-e1d80',
    authDomain: 'flutter-web-portfolio-e1d80.firebaseapp.com',
    storageBucket: 'flutter-web-portfolio-e1d80.appspot.com',
    measurementId: 'G-NZ1T97EZ9P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBs3kJDkDGmfoVxAtyBaZfwWt28ha_8xT8',
    appId: '1:338017368100:android:8b94b309ab1ee406a340b1',
    messagingSenderId: '338017368100',
    projectId: 'flutter-web-portfolio-e1d80',
    storageBucket: 'flutter-web-portfolio-e1d80.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAi37XoBr4ThKpO5hapecEmwKZx9RTYeeo',
    appId: '1:338017368100:ios:0667713dba4d246ea340b1',
    messagingSenderId: '338017368100',
    projectId: 'flutter-web-portfolio-e1d80',
    storageBucket: 'flutter-web-portfolio-e1d80.appspot.com',
    iosBundleId: 'com.park.flutterPortfolioWeb',
  );
}
